bashrc: add up function for navigation

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -33,6 +33,24 @@ pathprepend() {
   done
 }
 
+# navigate up the file hierarchy (Thanks to Derek Taylor (Distrotube))
+up() {
+    local d=""
+    local limit="$1"
+
+    if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+        limit=1
+    fi
+
+    for ((i=1; i<=limit; i++)); do
+        d="../$d"
+    done
+
+    if ! cd "$d"; then
+        echo "Couldn't go up $limit dirs."
+    fi
+}
+
 #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
 
 pathappend "${HOME}/scripts/general"
